services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - shared_network

  docStore:
    image: 'docker.io/library/document-store:0.0.1-SNAPSHOT'
    restart: always
    ports:
      - "8083:8083"
    expose:
      - "8083"
    build:
      context: .
    volumes:
      - ./logs:/workspace/logs
    depends_on:
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOKI_URL=http://loki:3100/loki/api/v1/push
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    networks:
      - shared_network

networks:
  shared_network:
    external: true
    name: shared_network
    driver: bridge

volumes:
  postgres_data: