services:
  keycloak:
    image: keycloak/keycloak
    ports:
      - '9090:8080'
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: start-dev --import-realm