scrape_configs:
  # The job name is added as a label 'job =< job_name>' to any timeseries scraped from this config.
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9091', 'localhost:9100', 'localhost:9113' ]

  - job_name: 'Spring Boot Applications'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8080','host.docker.internal:8081','host.docker.internal:8082','host.docker.internal:8083','host.docker.internal:8084']
        labels:
          application: "My Spring Boot Application"