spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    problemdetails:
      enabled: true
  application:
    name: document_store
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/CRMRealm
server:
  port: 8083