spring:
  application:
    name: ApiGateway
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:9090/realms/CRMRealm
        registration:
          kc1client:
            provider: keycloak
            client-id: crmclient
            client-secret: UAGMutFg200hRp3pfFomluDh7GAQ8epl
            scope:
              - openid
              - offline_access
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/crmclient