{
 "title": "Job Placement",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_cpu_seconds_total{}" }
   ]
  },
  {
   "title": "Api Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway usage and latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(scrape_duration_seconds{instance=\"host.docker.internal:8080\"}[$__interval])",
       "legendFormat": "Gateway api latency"
      }
     ]
    },
    {
     "title": "Gateway logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "{service_name=\"api-gateway\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Customer Relationship Management",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "CRM usage and latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(scrape_duration_seconds{instance=\"host.docker.internal:8081\"}[$__interval])",
       "legendFormat": "CRM api latency"
      }
     ]
    },
    {
     "title": "CRM logs",
     "type": "logs",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "{service_name=\"crm\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Document Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Document Store usage and latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(scrape_duration_seconds{instance=\"host.docker.internal:8083\"}[$__interval])",
       "legendFormat": "Gateway api latency"
      }
     ]
    },
    {
     "title": "Document Store logs",
     "type": "logs",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "expr": "{service_name=\"doc-store\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Analytics usage and latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(scrape_duration_seconds{instance=\"host.docker.internal:8084\"}[$__interval])",
       "legendFormat": "Analytics api latency"
      }
     ]
    },
    {
     "title": "Analytics Info logs",
     "type": "logs",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "{service_name=\"analytics\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Communication Manager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CM logs",
     "type": "logs",
     "gridPos": { "h": 15, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "{service_name=\"cm\"}"
      }
     ]
    }
   ]
  }
 ]
}