spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: Analytics
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/CRMRealm
server:
  port: 8084