spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  application:
    name: Analytics
  docker:
    compose:
      enabled: true
  r2dbc:
    url: r2dbc:pool:postgresql://postgres:5432/mydatabase
    username: myuser
    password: secret
    # driver-class-name: org.postgresql.Driver
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/CRMRealm
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: crm-analytics
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8084