spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  mvc:
    problemdetails:
      enabled: true
  application:
    name: CustomerRelationshipManagement
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/CRMRealm
server:
    port: 8081

#spring.sql.init.mode = always