spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true
  mvc:
    problemdetails:
      enabled: true
  application:
    name: CustomerRelationshipManagement
  datasource:
    url: jdbc:postgresql://localhost:5433/debezium_master?createDatabaseIfNotExist=true
    username: docker
    password: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/CRMRealm
  kafka:
    producer:
      bootstrap-servers: kafka:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      client-id: producer
server:
    port: 8081

#spring.sql.init.mode = always