spring:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://postgres:5432/debezium_master
    username: docker
    password: docker
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/CRMRealm
server:
  port: 8081