camel:
  component:
    google-mail-stream:
      application-name: 'WebAppOAuthClient'
      client-id: '677529689861-7hcila8392i0sc6jcbsov4raqr00bf6f.apps.googleusercontent.com'
      client-secret: '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'
      refresh-token: '1//04UKTwen3jvgDCgYIARAAGAQSNwF-L9Ir43Qwm18tkkbr6ZUetSEBrMF3gveb_qC3CHNIEkPq5T0gCo4odr7oGEkTTrMDnZK-fLg'
    google-mail:
      application-name: 'WebAppOAuthClient'
      client-id: '677529689861-7hcila8392i0sc6jcbsov4raqr00bf6f.apps.googleusercontent.com'
      client-secret: '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'
      refresh-token: '1//04UKTwen3jvgDCgYIARAAGAQSNwF-L9Ir43Qwm18tkkbr6ZUetSEBrMF3gveb_qC3CHNIEkPq5T0gCo4odr7oGEkTTrMDnZK-fLg'

spring:
  application:
    name: CommunicationManager
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/CRMRealm

server:
  port: 8082
