camel:
  component:
    google-mail-stream:
      application-name: 'WebAppOAuthClient'
      client-id: '677529689861-7hcila8392i0sc6jcbsov4raqr00bf6f.apps.googleusercontent.com'
      client-secret: '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'
      refresh-token: '1//04j6FATFdY212CgYIARAAGAQSNwF-L9IrhA9OGfS4cg7l9PrL2B6iClVOhRpaExABwmwr1dv2sNmB_gUP7DCLKAoycF6tdZul2pM'
    google-mail:
      application-name: 'WebAppOAuthClient'
      client-id: '677529689861-7hcila8392i0sc6jcbsov4raqr00bf6f.apps.googleusercontent.com'
      client-secret: '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'
      refresh-token: '1//04j6FATFdY212CgYIARAAGAQSNwF-L9IrhA9OGfS4cg7l9PrL2B6iClVOhRpaExABwmwr1dv2sNmB_gUP7DCLKAoycF6tdZul2pM'

spring:
  application:
    name: CommunicationManager
  kafka:
    bootstrap-servers: kafka:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:9090/realms/CRMRealm

server:
  port: 8082
